#!/usr/bin/env php
<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        require  $file;
        break;
    }
}

$options = [
    'action'  => 'help',
    'input' => [],
];

for ($i = 1; $i < $_SERVER['argc']; $i++) {
    switch ($_SERVER['argv'][$i]) {
        case '-l':
        case '--lint':
            $options['action'] = 'lint';
            break;
        case '-h':
        case '--help':
            $options['action'] = 'help';
            break;
        default:
            $input = $_SERVER['argv'][$i];
            if ('-' === substr($input, 0, 1)) {
                die('Unknown option ' . $input . PHP_EOL);
            }
            $options['input'][] = $input;
    }
}

if ('help' === $options['action']) {
    $help = <<<"HELP"
nacl [options] FILES...

Options:
    -h, --help      Display this help
    -l, --lint      Syntax check (lint)

HELP;
    die($help);
}

if (empty($options['input'])) {
    die('You must specify at least one input file.' . PHP_EOL);
}

$parser = Nuglif\Nacl\Nacl::createParser();

foreach ($options['input'] as $file) {
    try {
        $parser->parseFile($file);
        printf('No syntax errors detected in %s' . PHP_EOL, $file);
    } catch (Nuglif\Nacl\Exception $e) {
        printf('%s in %s on line %d' . PHP_EOL, $e->getMessage(), $e->getFile(), $e->getLine());
    }
}
